# Generated by Django 5.1.3 on 2025-05-22 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('nss_unit', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('date_of_birth', models.CharField(default='Not Provided', max_length=15)),
                ('username', models.CharField(default='default_username', max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('confirm_password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Coordinator',
                'verbose_name_plural': 'Coordinators',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='No description provided')),
                ('date', models.DateField()),
                ('time', models.TimeField(default='00:00')),
                ('location', models.CharField(default='No location provided', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Donation', 'Donation'), ('Misc', 'Misc')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100, unique=True)),
                ('student_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Unknown', max_length=200)),
                ('nss_unit_number', models.CharField(max_length=100)),
                ('admission_number', models.CharField(max_length=100)),
                ('roll_number', models.CharField(default='UNKNOWN', max_length=100)),
                ('course', models.CharField(default='Unknown', max_length=200)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email_id', models.EmailField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(default='Not provided')),
                ('date_of_birth', models.CharField(default='Not Provided', max_length=15)),
                ('blood_group', models.CharField(default='Not provided', max_length=5)),
                ('class_advisor', models.CharField(default='Not assigned', max_length=200)),
                ('username', models.CharField(default='default_username', max_length=150, unique=True)),
                ('password', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='camp.event')),
            ],
        ),
    ]
