# Generated by Django 5.1.3 on 2025-05-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_contactmessage'),
        ('camp', '0003_auto_20250522_2229'),
    ]

    operations = [
    ]
